### PR TITLE
Added JSDoc build system. Added docstrings to legion.js and legion/game.js.

### PR DESCRIPTION
**Pull request by chessmasterhong**
This pull request addresses issue #63, and an extraneous minor refactoring from long ago.

As per the initial requirements, a JSDoc build system has been put in place. Docstrings has been added to `legion.js` and `legion/game.js`. Documentations will be exported to the `./docs/` directory Tutorials has been configured to export into `./docs/tutorials/` directory. I specifically used these files as they seemed to have a sizable variation of items to docstring.

**Please review the docstrings for accuracy before accepting this pull request.** There are some items I am unsure about how to docstring it, such as what datatype some properties are or what the intended purpose (description) of some methods are, etc..

**Requirements:**
1. Run `npm install` to install the newly added JSDoc module.
2. Create a `./docs/` and `./docs/tutorials` directory.
3. Run `node node_modules/jsdoc/jsdoc.js -c ./jsdoc.conf.json` to generate the documentation.
4. Open `./docs/index.html` to view the document index page. The documentation should have navigation links to other pages based on what was defined in the docstrings.

_If rebuilding the documentation, you may want to clean the `./docs/` and `./docs/tutorials/` directories beforehand as JSDoc will not clean it for you. If not. It may also be in the best interest to write a script for this._

From my experience, I believe docstrings would best be placed at:
- global namespaces
- module level
- classes
- properties of classes
- methods of classes
- functions

I am currently using the default built-in JSDoc3 template. JSDoc documentation style can be modified using templates. One important thing to note is that although the code is fully documented via docstrings, it is the template that will dictate how the items will look when the documentation is generated. Some templates organizes classes differently, others will not display certain items unless the item belongs in a namespace, etc.

### CODE REVIEW

**Comment by DrkSephy** [comment]
+1, looks great Kevin! Once @docmarionum1 gives his +1, we'll merge this in.

**Comment by docmarionum1** [comment]
Don't worry about the comments not necessarily being right - I'll go through and fix/add details if necessary.  Just seeing the formatting is a big help! I've got a big change coming and part of it is going to be cleaning up all the code/docs/tests.

Can you make the small change I mentioned in environment?

**Comment by chessmasterhong** [comment]
I've made the change as mentioned.

**Comment by DrkSephy** [comment]
Looks great, merged!

**Pull request merged**
